server:
  port: 8083
  connectionTimeout: 5000
  tomcat:
    max-http-post-size: 0
    uri-encoding: UTF-8
    
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.0.109:30870/horus_dev2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: SCIIscii123
    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
#    continue-on-error: true
    hikari:
      connection-timeout: 3000
      minimum-idle: 2
      maximum-pool-size: 5
      auto-commit: true
      pool-name: DatebookHikariCP
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
          
mybatis-plus:
  mapper-locations: classpath:/com/sinocarbon/integral/mapper/*Mapper.xml
  type-aliases-package: com.sinocarbon.integral.pojo
  global-config.logic-delete-value: 0
  global-config.logic-not-delete-value: 1
  global-config.sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  
logging:
  config: classpath:logback-boot.xml
configService:
  uri: http://localhost:8087  