apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname}}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.appname}}
spec:
  selector:
    app: {{ .Values.appname}}
  ports:
  - name: http
    port: 8080
    targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.appname}}-v1
  namespace: {{ .Values.namespace}}
spec:
  replicas: {{ .Values.replicas}}
  template:
    metadata:
      labels:
        app: {{ .Values.appname}}
        version: v1
    spec:
      imagePullSecrets:      # 获取镜像需要的用户名密码
      - name: {{ .Values.aliyun.containerSrv.imagePullSecrets}}
      containers:
      - name: {{ .Values.appname}}
        image: {{ .Values.aliyun.containerSrv.region}}/{{ .Values.aliyun.containerSrv.namespace}}/{{ .Values.imagename}}
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: version
          value: v1
        ports:
        - name: http
          containerPort: 8080
